FileList = [
	"helpers/application.js"
	, "lib/file_cache.js"
	, "lib/authenticator.js"
	, "layouts/application.js"
	, "layouts/login.js"
	, "controllers/capsules.js"
	, "controllers/application.js"
	, "controllers/authentications.js"
	, "views/capsules/index.js"
	, "views/capsules/show.js"
	, "views/comments/show.js"
	, "views/photos/show.js"
	, "views/videos/show.js"
]
