FileList = [
	"helpers/application.js"
	, "helpers/images.js"
	, "ui/sub_tabs.js"
	, "ui/button_group.js"
	, "lib/file_cache.js"
	, "lib/geolocator.js"
	, "lib/authenticator.js"
	, "layouts/application.js"
	, "layouts/login.js"
	, "controllers/capsules.js"
	, "controllers/application.js"
	, "controllers/authentications.js"
	, "controllers/tags.js"
	, "views/capsules/index.js"
	, "views/capsules/show.js"
	, "views/capsules/create.js"
	, "views/capsules/mosaic.js"
	, "views/capsules/top_bar.js"
	, "views/capsules/update.js"
	, "views/comments/create.js"
	, "views/comments/show.js"
	, "views/photos/create.js"
	, "views/photos/show.js"
	, "views/videos/create.js"
	, "views/videos/show.js"
	, "views/tags/create.js"
]
